#!/usr/bin/env bash
#  a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
fname="/etc/passwd"
while IFS=":" read -r -a line
do
	uname="${line[0]}"
	grpid="${line[3]}"
	home="${line[5]}"
	cshell="${line[6]}"
	uid="${line[2]}"
	pw="${line[1]}"
	uinfo="${line[4]}"
	echo "The user $uname is part of the $grpid gang, lives in $home and rides $cshell. $uid's place is protected by the passcode $pw, more info about the user here: $uinfo"
done < "$fname"