#!/usr/bin/env bash
# a script that ollps in 10 itration displaying different strings in the 4th, 8th and other iteration

i=1

while [ $i -le 10 ]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	i=$((i+1))
done
