#!/usr/bin/env bash
# a bash script that displays the time for 12 hrs and 58min
hr=0

while [ $hr -le 12 ]
do
	min=1
	echo "Hour:" $hr
	while [ $min -le 59 ]
	do
		echo $min
		min=$((min+1))
	done
	hr=$((hr+1))
done