#!/usr/bin/env bash
# a script to configure an ubuntu server to change localhost to 127.0.0.2 and facebook to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo -e "\n8.8.8.8.8\tfacebook.com" >> ~/hosts.new
ep -f ~/hosts.new /etc/hosts